CREATE DATABASE 2021_CL112_KhodzhakhovE_Game;

USE 2021_CL112_KhodzhakhovE_Game;

DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
  id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20),
  Pass VARCHAR(20),
  PRIMARY KEY(id) 
);

DESCRIBE Users;

CREATE TABLE Levels(
  id INT NOT NULL AUTO_INCREMENT,
  FileName VARCHAR(20),
  W VARCHAR(20),
  H VARCHAR(20),
  Cnt VARCHAR(20),
  Fnl VARCHAR(20),
  PRIMARY KEY(id) 
);

DESCRIBE Levels;

CREATE TABLE Scores(
  id INT NOT NULL AUTO_INCREMENT,
  LevlId INT,
  UserID INT,
  Scroe VARCHAR(20),
  PRIMARY KEY(id) 
);

DESCRIBE Scores;